config/routes.rb
Rails.application.routes.draw do
  get 'friends/index'
  get 'friends/destroy'
  
  devise_for :users

  resources :users, only: [:edit, :update, :show] do
    resources :friendship_requests, only: [:create, :index, :update, :destroy]
    resources :friendships, only: [:index, :destroy]
  end

  resources :posts do
    resources :comments do
      resources :replies, except: :index
    end
  end

  resources :likes, only: [:create, :destroy]
 

  # Defines the root path route ("/")
  root "posts#index"
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :set_post, only: [:new, :create, :edit, :update]
  before_action :set_parent, only: [:new, :create]
  before_action :set_reply, only: [:show, :edit, :update, :destroy]

  def new
    @reply = @parent.replies.build
  end

  def create
    @reply = @parent.replies.build(reply_params)
    @reply.user = current_user
    @reply.post = @post

    if @reply.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
    puts "@reply is set to: #{@reply.id}"
  end

  def update
    if @reply.update(reply_params)
      redirect_to post_path(@post)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = @reply.post
    @reply.destroy
    redirect_to post_path(@post)
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
  def set_parent
    @parent = Comment.find(params[:comment_id])
  end


  def set_reply
    @reply = Comment.find(params[:id])
  end

  def reply_params
    params.require(:comment).permit(:body, :parent_id, :image)
  end
end

app/views/replies/_reply.html.erb
<div class="container d-flex flex-row">
  <div>
    <% if reply.user.avatar.attached? %>
      <%= image_tag reply.user.avatar.variant(resize_to_limit: [50,50]), class:"rounded-circle" %>
    <% end %>
  </div>
  <div class="ms-3">
    <span class="h6"> <%= reply.user.name %> </span>
    <span class="float-end">
      <% if user == reply.user %>
        <%= link_to inline_svg_tag("svgs/pencil.svg", size: "15px"), "/posts/#{reply.post.id}/comments/#{reply.parent.id}/replies/#{reply.id}/edit" %>
        <%= link_to inline_svg_tag("svgs/trash-can.svg", size: "15px"), "/posts/#{reply.post.id}/comments/#{reply.parent.id}/replies/#{reply.id}", data: {
                                turbo_method: :delete,
                                turbo_confirm: "Are you sure?" }%>
      <% end %>
    </span>
    <%= turbo_frame_tag "edit_reply" do %>
        <p><%= reply.body %></p>
        <% if reply.image.attached?%>
          <%= image_tag reply.image.variant(resize_to_limit: [300, nil]) %>
        <% end %>

      <% if reply.liked_by?(user) %>
        <% like = Like.find_by(user_id: user.id, likable_id: reply.id, likable_type: "Comment")%>
        <%= link_to inline_svg_tag("svgs/thumb-up.svg", size: "25px"), "like/#{like.id}", method: :delete %>
      <% else %>
        <%= link_to inline_svg_tag("svgs/thumb-up-outline.svg", size: "25px"), likes_path(likable_id: reply.id, likable_type: "comment"), method: :post %>
      <% end %>
      <span class="float-end">
        <%= reply.likes.count %> <%= reply.likes.count == 1 ? "Like" : "Likes" %>
      </span>
    <% end %>
  </div>
</div>

app/views/replies/edit.html.erb
<%= turbo_frame_tag "edit_reply" do %>
  <% if @reply.errors.any? %>
    <div id="error_explanation">
      <h6><%= pluralize(@reply.errors.count, "error") %> prohibited this article from being saved:</h6>

      <ul>
        <% @reply.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with model: [@post, @reply], url: post_comment_reply_path(@post, @comment, @reply, comment_id: params[:comment_id], post_id: params[:post_id], id: params[:id]), method: :patch do |form| %>
    <div class="d-block input-group border">
      <div>
        <%= form.text_area :body, class:"form-control border-none" %>
      </div>
      <div>
        <label for="image-upload">
          <span role="button" class="ms-4"> <%= inline_svg_tag("svgs/image.svg", size: "24px") %></span>
        </label>
        <%= form.file_field :image, id: "image-upload", class: "d-none" %>
      
        <span class="float-end me-4">
          <%= form.button(type: 'submit', class: "btn btn-link p-0") do %>
            <%= inline_svg_tag('svgs/send.svg', size: '24px') %>
          <% end %>
      </span>
      </div>
    </div>
  <% end %>
<% end %>

app/views/replies/new.html.erb
<%= turbo_frame_tag "new_reply" do %>
  <% if @reply.errors.any? %>
    <div id="error_explanation">
      <h6><%= pluralize(@reply.errors.count, "error") %> prohibited this article from being saved:</h6>

      <ul>
        <% @reply.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with model: [@post, @parent], url: post_comment_replies_path(@post, @comment, comment_id: params[:comment_id]), method: :post do |form| %>
    <div class="d-block input-group bg-light-blue border">
      <%= form.hidden_field :parent_id, value: params[:parent_id] %>
      <div>
        <%= form.text_area :body, class: "form-control bg-light-blue border-none" %>
      </div>
      <div>
        <label for="image-upload">
          <span role="button" class="ms-4"> <%= inline_svg_tag("svgs/image.svg", size: "24px") %></span>
        </label>
        <%= form.file_field :image, id: "image-upload", class: "d-none" %>

        <span class="float-end me-4">
          <%= form.button(type: 'submit', class: "btn btn-link p-0") do %>
            <%= inline_svg_tag('svgs/send.svg', size: '24px') %>
          <% end %>
        </span>
    </div>
  <% end %>
<% end %>

app/views/replies/show.html.erb
<%= render "replies/reply", reply: @reply, user: current_user %>