config/routes.rb
Rails.application.routes.draw do
  get 'friends/index'
  get 'friends/destroy'
  
  devise_for :users

  resources :users, only: [:edit, :update, :show] do
    resources :friendship_requests, only: [:create, :index, :update, :destroy]
    resources :friendships, only: [:index, :destroy]
  end

  resources :posts do
    resources :comments do
      resources :replies, except: :index
    end
  end

  resources :likes, only: [:create, :destroy]
 

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true
  
  belongs_to :user
  belongs_to :post
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :replies, class_name: 'Comment', foreign_key: 'parent_id', dependent: :destroy

  has_many :likes, as: :likable

  has_one_attached :image

  def liked_by?(user)
    Like.find_by(user_id: user.id, likable_id: self.id, likable_id: "Comment")
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:new, :create, :index]
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def new
    @comment = @post.comments.build
  end

  def create
    @comment = @post.comments.build(comment_params)

    @comment.user = current_user

    if @comment.save
      redirect_to post_path(@post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def index
    @comments = @post.comments.all
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to post_path(@comment.post)
    else 
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = @comment.post
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :image)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
 <div class="container d-flex flex-row" >
  <div>
    <% if comment.user.avatar.attached? %>
      <%= image_tag comment.user.avatar.variant(resize_to_limit: [50,50]), class:"rounded-circle" %>
    <% end %>
  </div>
  <div class="ms-3 flex-grow-1">
    <span class="h6"> <%= comment.user.name %> </span>
    <span class="float-end">
      <% if user == comment.user %>
        <%= link_to inline_svg_tag("svgs/pencil.svg", size: "15px"), "/posts/#{comment.post.id}/comments/#{comment.id}/edit" %>
        <%= link_to inline_svg_tag("svgs/trash-can.svg", size: "15px"), "/posts/#{comment.post.id}/comments/#{comment.id}", data: {
                                    turbo_method: :delete,
                                    turbo_confirm: "Are you sure?" }%>
      <% end %>
    </span>
    <%= turbo_frame_tag "edit_comment" do %>
        <div class="bg-light-blue rounded p-1">
          <p><%= comment.body %></p>
          <% if comment.image.attached?%>
            <%= image_tag comment.image.variant(resize_to_limit: [300, nil]), class: "mx-auto d-block rounded" %>
          <% end %>
        </div>
        <% if comment.liked_by?(user) %>
          <% like = Like.find_by(user_id: user.id, likable_id: comment.id, likable_id: "Comment")%>
          <%= link_to inline_svg_tag("svgs/thumb-up.svg", size: "25px"), "like/#{like.id}", method: :delete %>
        <% else %>
          <%= link_to inline_svg_tag("svgs/thumb-up-outline.svg", size: "25px"), likes_path(likable_id: comment.id, likable_type: "Comment"), method: :post %>
        <% end %>
        <span class="float-end">
          <%= comment.likes.count %> <%= comment.likes.count == 1 ? "like" : "likes" %>
          <%= comment.replies.count %> <%= comment.replies.count == 1 ? "reply" : "replies" %>
        </span>
        
      <% end %>
    <div>  
      <%= turbo_frame_tag "new_reply" do %>
        <%= link_to "reply", new_post_comment_reply_path(comment.post, comment, parent_id: comment.id), class: "text-decoration-none text-secondary" %>
      <% end %>
    </div>

    <% if comment.replies.any? %>
      <div class="container">
        <h6> Replies </h6>
        <% comment.replies.each do |reply| %>
          <%= render 'replies/reply', reply: reply, user: user %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/edit.html.erb
<%= turbo_frame_tag "edit_comment" do %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h6><%= pluralize(@comment.errors.count, "error") %> prohibited this article from being saved:</h6>

      <ul>
        <% @comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with model: [@post, @comment], url: post_comment_path(@post, @comment, post_id: params[:post_id], id: params[:id]), method: :patch do |form| %>
    <div class="d-block input-group bg-light-blue border">
      <%= form.hidden_field :parent_id, value: params[:parent_id] %>
      <div>
        <%= form.text_area :body, class: "form-control bg-light-blue border-none" %>
      </div>
      <div>
        <label for="image-upload">
          <span role="button" class="ms-4"> <%= inline_svg_tag("svgs/image.svg", size: "24px") %></span>
        </label>
        <%= form.file_field :image, id: "image-upload", class: "d-none" %>

        <span class="float-end me-4">
          <%= form.button(type: 'submit', class: "btn btn-link p-0") do %>
            <%= inline_svg_tag('svgs/send.svg', size: '24px') %>
          <% end %>
        </span>
    </div>
    
  <% end %>
<% end %>

app/views/comments/new.html.erb
<%= turbo_frame_tag "new_comment" do %> 
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h6><%= pluralize(@comment.errors.count, "error") %> prohibited this article from being saved:</h6>

      <ul>
        <% @comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= render partial: 'shared/form', locals: { model: [@comment.post, @comment], parent_id: nil } %>
<% end %>

app/views/comments/show.html.erb
<%= render "comments/comment.html.erb" comment: @comment, user: current_user %>