config/routes.rb
Rails.application.routes.draw do
  get 'friends/index'
  get 'friends/destroy'
  
  devise_for :users

  resources :users, only: [:edit, :update, :show] do
    resources :friendship_requests, only: [:create, :index, :update, :destroy]
    resources :friendships, only: [:index, :destroy]
  end

  resources :posts do
    resources :comments do
      resources :replies, except: :index
    end
  end

  resources :likes, only: [:create, :destroy]
 

  # Defines the root path route ("/")
  root "posts#index"
end

app/views/shared/_form.html.erb
<%= form_with model: model do |form| %>
  <div class="d-block input-group bg-light-blue border">
    <% if params[:parent_id] %>
      <%= form.hidden_field :parent_id, value: params[:parent_id] %>
    <% end %>
    <div>
      <%= form.text_area :body, class: "form-control bg-light-blue border-none" %>
    </div>
    <div>
      <label for="image-upload">
        <span role="button" class="ms-4"> <%= inline_svg_tag("svgs/image.svg", size: "24px") %></span>
      </label>
      <%= form.file_field :image, id: "image-upload", class: "d-none" %>

      <span class="float-end me-4">
        <%= form.button(type: 'submit', class: "btn btn-link p-0") do %>
          <%= inline_svg_tag('svgs/send.svg', size: '24px') %>
        <% end %>
      </span>
    </div>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<ul class="nav flex-column">
  <li class="nav-item">
    <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Posts", posts_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Friends", user_friendships_path(current_user), class: "nav-link"%>
  </li>
</ul>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-sm shadow">
  <div class="container-fluid">
    <%= link_to "OdinBook", root_path, class: "navbar-brand " %>
    <ul class="navbar-nav float-lg-end">
      <% if user_signed_in?%>
        <li class="nav-item ms-2">
          <%= link_to current_user.name, user_path(current_user), class: "nav-link align-middle" %>
        </li>

        <li class="nav-item ms-2">
          <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link align-middle" %>
        </li>

        <li class="nav-item ms-2">
          <%= link_to "Notifications", user_friendship_requests_path(user_id: current_user.id), class: "nav-link align-middle"%>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_post_template.html.erb
<div>
  <%= turbo_frame_tag "edit_post" do %>
    <%= post.body %>
    <% if current_user == post.user %>
      <%= link_to "Edit", edit_post_path(post) %>
      <%= link_to "Delete", @post, data: {
                            turbo_method: :delete,
                            turbo_confirm: "Are you sure?" }%>
    <% end %>
  <% end %>
</div>