config/routes.rb
Rails.application.routes.draw do
  get 'friends/index'
  get 'friends/destroy'
  
  devise_for :users

  resources :users, only: [:edit, :update, :show] do
    resources :friendship_requests, only: [:create, :index, :update, :destroy]
    resources :friendships, only: [:index, :destroy]
  end

  resources :posts do
    resources :comments do
      resources :replies, except: :index
    end
  end

  resources :likes, only: [:create, :destroy]
 

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  validates :body, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likable

  has_one_attached :image

  # after_create_commit -> { broadcast_prepend_to "posts", partial: "posts/post", locals: { post: self, user: self.user } }
  # after_update_commit -> { broadcast_replace_to "posts", partial: "posts/post", locals: { post: self, user: self.user } }
  
  def liked_by?(user)
    Like.find_by(user_id: user.id, likable_id: self.id, likable_id: "post")
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorise_user, only: [:edit, :update, :destroy]

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to post_path(@post)
    else
      render :new, status: :unpropcessable_entity
    end
  end

  def index
    @user = User.includes(friends: :posts).find(current_user.id)
    friend_post_ids = @user.friends.map { |friend| friend.posts.pluck(:id) }.flatten
    post_ids = @user.posts.pluck(:id) + friend_post_ids
    @posts = Post.find(post_ids)
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to user_path(current_user), status: :see_other
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def authorise_user
    unless current_user == @post.user
      flash[:alert] = "You are not authorized to perfeorm this action."
      redirect_to user_path(current_user)
    end
  end

  def post_params
    params.require(:post).permit(:body, :image)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="container bg-white shadow rounded-3 mb-3 p-3" >
  <% if post.user.avatar.attached? %>
    <%= image_tag post.user.avatar.variant(resize_to_limit: [50,50]), class:"rounded-circle" %>
  <% end %>
  <span class="h4"> <%= post.user.name %> </span>
  <span class="float-end">
    <% if user == post.user %>
      <%= link_to inline_svg_tag("svgs/pencil.svg", size: "15px"), edit_post_path(post) %>
      <%= link_to inline_svg_tag("svgs/trash-can.svg", size: "15px"), post_path(post), data: {
                                turbo_method: :delete,
                                turbo_confirm: "Are you sure?" }%>
    <% end %>
  </span>
  <%= turbo_frame_tag "edit_post" do %>
    <p class="px-3 mt-2" ><%= post.body %></p>
    <% if post.image.attached? %>
      <%= image_tag post.image.variant(resize_to_limit: [600, nil]), class: "mx-auto d-block rounded" %>
    <% end %>
    
    <div>
      <span class="text-secondary"><%= post.likes.count %> <%= post.likes.count == 1 ? "like" : "likes" %></span>
      <span class="float-end text-secondary"><%= post.comments.count %> <%= post.comments.count == 1 ? "comment" : "comments" %></span>
    </div>
  <% end %>
  <hr />
  <% if post.liked_by?(user) %>
    <% like = Like.find_by(user_id: user.id, likable_id: post.id, likable_type: "Post")%>
    <%= link_to inline_svg_tag("svgs/thumb-up.svg", size: "25px"), "like/#{like.id}", method: :delete, class: "ms-5" %>
  <% else %>
    <%= link_to inline_svg_tag("svgs/thumb-up-outline.svg", size: "25px"), likes_path(likable_id: post.id, likable_type: "Post"), method: :post, class: "ms-5" %>
  <% end %>
  <%= turbo_frame_tag "new_comment" do %>
    <%= link_to inline_svg("svgs/comment-outline", size: "25px"), new_post_comment_path(post), class: "float-end me-5" %>
  <% end %>
  <hr />

  <% if post.comments.any? %>
    <div class="container">
      <h5> Comments </h5>
      <% post.comments.each do |comment| %>
        <% if comment.parent == nil %>
          <%= render 'comments/comment', comment: comment, user: user %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= turbo_frame_tag "edit_post" do %>
  <%= render "shared/form", model: @post %>
<% end %>

app/views/posts/index.html.erb
<%# turbo_stream_from "posts" %>

<div class="row">
  <div class="col-sm-4">
    <%= render "shared/menu"%>
  </div>

  <div class="col-lg-6 col-sm-8">
    <%= turbo_frame_tag "new_post" do %>
      <div class="mb-5 text-center">
        <%= link_to "Create a new post", new_post_path, class: "btn btn-primary" %>
      </div>
    <% end %>
    

    <% if @posts.any? %>
      <% @posts.each do |post|%>
        <%= render 'posts/post', post: post, user: current_user %>
      <% end %>
    <% end %>
  </div>
</div>


app/views/posts/new.html.erb
<% turbo_frame_tag "new_post" do %>
  <%= render "shared/form", model: @post %>
<% end %>


app/views/posts/show.html.erb
<%= render 'posts/post', post: @post, user: current_user %>